### ISSUE TITLE
python3-mb: exception message when using an unknown option

### ISSUE THREAD

**Issue by pimzand** [jack-cli-cd-ripper/jack#12]
unknown option `--whatever'
Traceback (most recent call last):
  File "/usr/local/bin/jack", line 80, in <module>
    help, argv_cf = jack.argv.parse_argv(cf, sys.argv)
  File "/usr/local/lib/python3.8/site-packages/jack/argv.py", line 229, in parse_argv
    show_usage(cf)
TypeError: show_usage() missing 1 required positional argument: 'longhelp'

**Comment by zzarne** [comment]
Fixed in 3498aa96.
