### ISSUE TITLE
Build fails on current releases of Debian/Ubuntu systems.

### ISSUE THREAD

**Issue by daleamon** [jack-cli-cd-ripper/jack#57]
The latest version from this repository fails to build on

```
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo

```
```
/usr/lib/python3/dist-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
[12/08/23 11:58:48] WARNING  toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section' pyproject_reading.py:42
Traceback (most recent call last):
  File "/home/amon/Desktop/TASK-JackPython3/20230919-jack-python3/jack-python3-mb/./setup.py", line 28, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 485, in __init__
    _Distribution.__init__(
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 926, in finalize_options
    ep(self)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 946, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/home/amon/Desktop/TASK-JackPython3/20230919-jack-python3/jack-python3-mb/.eggs/setuptools_scm-8.0.4-py3.11.egg/setuptools_scm/_integration/setuptools.py", line 101, in version_keyword
    _assign_version(dist, config)
  File "/home/amon/Desktop/TASK-JackPython3/20230919-jack-python3/jack-python3-mb/.eggs/setuptools_scm-8.0.4-py3.11.egg/setuptools_scm/_integration/setuptools.py", line 56, in _assign_version
    _version_missing(config)
  File "/home/amon/Desktop/TASK-JackPython3/20230919-jack-python3/jack-python3-mb/.eggs/setuptools_scm-8.0.4-py3.11.egg/setuptools_scm/_get_version_impl.py", line 112, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /home/amon/Desktop/TASK-JackPython3/20230919-jack-python3/jack-python3-mb.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by C0RD** [comment]
I rebuild the package and then found that I lack a working cd-player to test it ;-)

The build is here: https://cord.de/files/Public/jack/ . If it works i'll upload it to Debian.

I add my debian/rules and debian/control files:

debian/rules
```
#!/usr/bin/make -f

export PYBUILD_NAME=jack
export SETUPTOOLS_SCM_PRETEND_VERSION=$(shell dpkg-parsechangelog -S version |sed -e 's/~/+/g')

%:
	dh $@ --with=python3 --buildsystem=pybuild
```

debian/control

```
Source: jack
Section: sound
Priority: optional
Maintainer: Cord Beermann <cord@debian.org>
Rules-Requires-Root: no
Build-Depends: debhelper-compat (= 13), dh-python, python3-dev, python3-setuptools-scm, python3-pip
Standards-Version: 4.6.2
Homepage: https://github.com/jack-cli-cd-ripper/jack

Package: jack
Architecture: all
Depends: ${python3:Depends}, ${shlibs:Depends}, ${misc:Depends}, python3-willow, vorbis-tools | flac | lame | fdkaac, cdparanoia | icedax
Description: Rip and encode CDs with one command
 Jack has been developed with one main goal: making OGGs (or MP3s)
 without having to worry. There is nearly no way that an incomplete rip
 goes unnoticed, e.g. jack compares WAV and OGG file sizes when
 continuing from a previous run. Jack also checks your HD space before
 doing anything (even keeps some MB free).

```

**Comment by daleamon** [comment]
Thank you and a Merry Christmas to you and also to Arne. Your test build installs cleanly. I'm currently testing it with a CD and have no issues thus far. I'll get back to you in a few minutes when I can confirm I have playable tracks.

**Comment by daleamon** [comment]
Confirm. Ripped 30 tracks and played two at random.

**Comment by daleamon** [comment]
Ah, I spoke too soon. There is no jack.freedb file for me to edit. Perhaps I should copy a file from a different CD and set it up manually?

**Comment by daleamon** [comment]
Don't see an /etc/jackrc or a ~/.jack3rc file either.

**Comment by daleamon** [comment]
I saved a copy to a temp folder, created a jack.freedb file from scratch, took the CD out because it kept trying to redo it, and I got the following:
```
amon:~/jack$ ls
jack.freedb       track_03.mp3  track_10.mp3  track_17.mp3  track_24.mp3
jack.freedb~      track_04.mp3  track_11.mp3  track_18.mp3  track_25.mp3
jack.musicbrainz  track_05.mp3  track_12.mp3  track_19.mp3  track_26.mp3
jack.progress     track_06.mp3  track_13.mp3  track_20.mp3  track_27.mp3
jack.toc          track_07.mp3  track_14.mp3  track_21.mp3  track_28.mp3
track_01.mp3      track_08.mp3  track_15.mp3  track_22.mp3  track_29.mp3
track_02.mp3      track_09.mp3  track_16.mp3  track_23.mp3  track_30.mp3

amon@otv3:~/jack$ jack -R
This is jack 4+git20230906.795fba0.1 (C)2022 Arne Zellentin, Pim Zandbergen.
https://github.com/jack-cli-cd-ripper/jack
 *warning* You have no standard location set, putting files into the current
           directory. Please consider setting base_dir in ~/.jack4rc.
 *error* Access of CD device /dev/cdrom resulted in error: cannot read table of
         contents
```

**Comment by C0RD** [comment]
> Don't see an /etc/jackrc or a ~/.jack3rc file either.

I think that should be a ~/.jack4rc now, which can be regenerated with 

`jack --save`

**Comment by C0RD** [comment]
> Ah, I spoke too soon. There is no jack.freedb file for me to edit. Perhaps I should copy a file from a different CD and set it up manually?

as the Authors have worked on that and musicbrainz also came in, this might also be a thing that you need to configure.

**Comment by daleamon** [comment]
Yes, it's quite important because I often manually create jack.freedb files on my own rehearsal or live tapes as well as collections of singles I put together.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by C0RD** [comment]
Jack has been uploaded to Debian again. https://packages.debian.org/source/unstable/jack

**Comment by daleamon** [comment]
Curious. Does this fix the problem with reading jack.freedb files? If others are like me and have large music collections... I have several thousands of them and its my prefered method to add new albums with emacs jack.freedb

________________________________________

**Comment by daleamon** [comment]
emacs jack.freedb

**Comment by daleamon** [comment]
emacs jack.freedb
jack -C -R

excuse the extra posts... my phone and my laptop use different chars to insert \n

**Comment by C0RD** [comment]
If that is not working please open a new ticket in the tracker. 

This ticket is about building from source, and at least for Debian this has been fixed.

@zzarne I think this ticket can be closed.

**Comment by daleamon** [comment]
If anyone is interested, I have a program that handles the -C -R using the old jack files. I cannot be the only one with thousands of albums using it.


________________________________________
